### PR TITLE
Modify Meridian toggle, remove zero hour when show-meridian='true'

### PR DESCRIPTION
**Pull request by mikeacosta**
- Modify Meridian to toggle from 11:00 AM to 12:00 PM and from 12:00 AM to 11:00 PM
- Remove zero hour when show-meridian='true'

### CODE REVIEW

**Comment by mikeacosta** [comment]
Great directive.  Some minor changes I made based on feedback from users.

**Comment by jkuri** [comment]
Hi @mikeacosta, thanks for this! If you are interested to develop and maintain this component further I can add you as a collaborator?

**Comment by mikeacosta** [comment]
@jkuri Yes, that would be great!

**Comment by jkuri** [comment]
@mikeacosta I added you as a collaborator, you now have push access to this repository. Thanks for helping!

**Pull request merged**
